# Generated by Django 3.2.23 on 2023-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], default='choice1', max_length=24),
        ),
    ]
