# Generated by Django 3.2.23 on 2023-12-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_content_post_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grossscore',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='post',
            name='stableford',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tees_played_off',
            field=models.CharField(default='White', max_length=10),
        ),
    ]
